### ISSUE TITLE
Updated build

### ISSUE THREAD

**Issue by donferi** [lukeapage/eslint-plugin-switch-case#26]
Hi Luke,

I've been using this plugin for a while and I love it. There are some scenarios where writing switch statements in some weird ways causes this plugin to crash.

I don't feel I have the skills to fix the plugin, but I was thinking on adding a couple of test cases so it would be helpful for somebody else to fix if they wanted. However, I was not able to run the repo, trying to run the tests causes a bunch of errors that I'm guessing is from old dependencies.

**Comment by lukeapage** [comment]
Thanks.

I've updated all dependencies, feel free to make a PR now.
